from __future__ import annotations

import math
import re
import unicodedata
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

from bson import ObjectId
from sqlalchemy import or_, select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from ..models.model_postgre import Chunk, Class, Image, Keyword, Lesson, Subject, Topic, Video
from .keyword_embedding import embed_keyword_cached
from .gemini_topic_expander import expand_topic_keywords_debug

_TOKEN_RE = re.compile(r"[0-9A-Za-zÀ-ỹ]+", flags=re.UNICODE)

# bump this when you replace the file so you can confirm the running code
_SERVICE_VERSION = "search_chunk_with_media_v10_alias_reverse_accent_fix"


# Vietnamese-ish stop words + a few generic fillers. Keep it small; we just want to avoid
# building concepts from "tài liệu", "về", ... which makes lexical matching too broad.
_STOP = {
    "tài", "liệu", "về", "của", "cho", "là", "các", "những", "một", "này", "đó",
    "ở", "trong", "và", "hoặc", "the", "a", "an", "of", "to", "in",
    "tìm", "kiếm", "cho", "tôi", "xin", "hãy", "cần", "muốn", "liên", "quan",
    "đến", "cái", "nào", "có", "không", "với", "giúp", "dạng",
}

# Alias map to improve recall for child concepts generated by Gemini.
# Keep this intentionally small and domain-focused so search does not become too broad.
_EXPANSION_ALIASES: Dict[str, List[str]] = {
    "cpu": ["cpu", "bộ xử lý", "bộ xử lý trung tâm", "bo xu ly", "bo xu ly trung tam", "vi xử lý", "vi xu ly", "processor"],
    "gpu": ["gpu", "card đồ họa", "card do hoa", "cạc đồ họa", "cac do hoa", "bộ xử lý đồ họa", "bo xu ly do hoa", "graphics card", "graphic card", "video card"],
    "ram": ["ram", "bộ nhớ ram", "bo nho ram", "bộ nhớ", "bo nho", "random access memory"],
    "rom": ["rom", "bộ nhớ rom", "bo nho rom", "read only memory"],
    "ssd": ["ssd", "ổ cứng ssd", "o cung ssd", "ổ thể rắn", "o the ran", "solid state drive"],
    "hdd": ["hdd", "ổ cứng hdd", "o cung hdd", "ổ đĩa cứng", "o dia cung", "hard disk", "hard disk drive"],
    "mainboard": ["mainboard", "main board", "bo mạch chủ", "bo mach chu", "bảng mạch chủ", "bang mach chu", "motherboard"],
    "motherboard": ["motherboard", "bo mạch chủ", "bo mach chu", "mainboard", "main board"],
    "psu": ["psu", "bộ nguồn", "bo nguon", "power supply", "nguồn máy tính", "nguon may tinh"],
    "vga": ["vga", "gpu", "card đồ họa", "card do hoa", "cạc đồ họa", "cac do hoa", "graphics card"],
}


def _strip_accents(s: str) -> str:
    s = (s or "").replace("đ", "d").replace("Đ", "D")
    return "".join(ch for ch in unicodedata.normalize("NFD", s) if unicodedata.category(ch) != "Mn")


def _norm_spaces(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip())


def _norm_key(s: str) -> str:
    return _norm_spaces(_strip_accents((s or "").lower()))


_ALIAS_TO_CANONICAL: Dict[str, str] = {}
for _canonical, _aliases in _EXPANSION_ALIASES.items():
    for _raw in [_canonical] + list(_aliases):
        _k = _norm_key(_raw)
        if _k and _k not in _ALIAS_TO_CANONICAL:
            _ALIAS_TO_CANONICAL[_k] = _canonical


def _like_pat(term: str) -> str:
    """ILIKE pattern tolerant to '_' / multiple separators.

    Example: 'phần cứng' -> '%phần%cứng%'
    This matches 'phần cứng', 'phần_cứng', 'phần---cứng', ...
    """

    t = _norm_spaces((term or "").lower())
    if not t:
        return "%"
    t = t.replace(" ", "%")
    return f"%{t}%"


def _tokens_no_stop(q: str) -> list[str]:
    s = (q or "").strip().lower()
    if not s:
        return []
    raw = [t for t in _TOKEN_RE.findall(s) if t]
    toks = [t for t in raw if t not in _STOP and len(t) >= 2]
    return toks

def _core_query_text(q: str) -> str:
    return _norm_spaces(" ".join(_tokens_no_stop(q)))


def _is_generic_query(core_query: str, tokens: list[str]) -> bool:
    q = _norm_spaces((core_query or '').lower())
    generic_phrases = {
        "thông tin", "dữ liệu", "máy tính", "tin học", "thiết bị số",
        "xử lí thông tin", "xử lý thông tin", "công nghệ", "internet",
    }
    if q in generic_phrases:
        return True
    return len(tokens) <= 1


def _max_expand_terms(core_query: str, tokens: list[str], exact_hit_count: int) -> int:
    if _is_generic_query(core_query, tokens):
        return 0
    if exact_hit_count >= 8:
        return 0
    if exact_hit_count >= 6:
        return 3
    if exact_hit_count >= 4:
        return 6
    if len(tokens) >= 4:
        return 12
    if len(tokens) == 3:
        return 10
    if len(tokens) == 2:
        return 8
    return 6


def _term_aliases(term: str) -> List[str]:
    raw = _norm_spaces((term or "").lower())
    if not raw:
        return []

    canonical = _ALIAS_TO_CANONICAL.get(_norm_key(raw), raw)
    out: List[str] = []
    for cand in [canonical] + _EXPANSION_ALIASES.get(canonical, []) + [raw]:
        norm = _norm_spaces((cand or "").lower())
        if norm and norm not in out:
            out.append(norm)
    return out


def _term_variants(term: str) -> List[str]:
    t = _norm_spaces((term or "").lower())
    if not t:
        return []

    variants: List[str] = []
    for alias in _term_aliases(t):
        if alias not in variants:
            variants.append(alias)

        collapsed = alias.replace(" ", "")
        if len(collapsed) >= 3 and collapsed not in variants:
            variants.append(collapsed)

    return variants


def _canonical_term_label(term: str) -> str:
    aliases = _term_aliases(term)
    return aliases[0] if aliases else _norm_spaces((term or "").lower())


def _filter_terms_with_db_hits(*, pg: Session, terms: List[str], cand_chunks: Optional[List[str]], limit: int) -> List[str]:
    out: List[str] = []
    seen: set[str] = set()

    for term in terms:
        canonical = _canonical_term_label(term)
        if not canonical or canonical in seen:
            continue

        variants = _term_variants(term)
        has_hit = any(_pg_term_has_hit(pg=pg, term=variant, cand_chunks=cand_chunks) for variant in variants)
        if has_hit:
            seen.add(canonical)
            out.append(canonical)
        if len(out) >= limit:
            break

    return out


def _merge_seed_and_expanded(seed_ids: List[str], expanded_ids: List[str], max_extra: int = 12) -> List[str]:
    out: List[str] = []
    seen: set[str] = set()
    for cid in seed_ids:
        if cid and cid not in seen:
            seen.add(cid)
            out.append(cid)
    added = 0
    for cid in expanded_ids:
        if cid and cid not in seen:
            seen.add(cid)
            out.append(cid)
            added += 1
        if added >= max_extra:
            break
    return out


def _pg_term_has_hit(*, pg: Session, term: str, cand_chunks: Optional[list[str]]) -> bool:
    """Return True if term or one of its variants appears in PG keyword_name OR chunk_name."""

    variants = _term_variants(term)
    if not variants:
        return False

    for variant in variants:
        pat = _like_pat(variant)
        try:
            stmt = select(Keyword.keyword_id).where(Keyword.keyword_name.ilike(pat))
            if cand_chunks is not None:
                if len(cand_chunks) == 0:
                    return False
                stmt = stmt.where(Keyword.chunk_id.in_(cand_chunks))
            stmt = stmt.limit(1)
            if list(pg.execute(stmt).all()):
                return True
        except Exception:
            pass

        try:
            stmt2 = select(Chunk.chunk_id).where(Chunk.chunk_name.ilike(pat))
            if cand_chunks is not None:
                if len(cand_chunks) == 0:
                    return False
                stmt2 = stmt2.where(Chunk.chunk_id.in_(cand_chunks))
            stmt2 = stmt2.limit(1)
            if list(pg.execute(stmt2).all()):
                return True
        except Exception:
            pass

    return False


def _segment_concepts_partial(*, pg: Session, tokens: list[str], cand_chunks: Optional[list[str]]) -> tuple[list[str], int]:
    """Greedy longest-match segmentation into phrases/unigrams that exist in data.

    Returns:
      - concepts found in order
      - number of covered tokens

    Unlike strict mode, this does not require full coverage. This lets us keep the
    strongest phrase as an anchor when the full query is too restrictive, e.g.
    'phần cứng máy tính' where the chunk has 'phần cứng' but not the extra context.
    """

    if not tokens:
        return [], 0

    n = len(tokens)
    max_ngram = 5
    out: list[str] = []
    i = 0
    covered = 0

    while i < n:
        found = None
        for L in range(min(max_ngram, n - i), 1, -1):
            phrase = " ".join(tokens[i : i + L])
            if _pg_term_has_hit(pg=pg, term=phrase, cand_chunks=cand_chunks):
                found = phrase
                out.append(phrase)
                i += L
                covered += L
                break

        if found:
            continue

        t = tokens[i]
        if _pg_term_has_hit(pg=pg, term=t, cand_chunks=cand_chunks):
            out.append(t)
            covered += 1
        i += 1

    seen = set()
    dedup = []
    for c in out:
        if c and c not in seen:
            seen.add(c)
            dedup.append(c)

    return dedup[:8], covered


def _segment_concepts_strict(*, pg: Session, tokens: list[str], cand_chunks: Optional[list[str]]) -> list[str]:
    concepts, covered = _segment_concepts_partial(pg=pg, tokens=tokens, cand_chunks=cand_chunks)
    return concepts if covered >= len(tokens) else []


def _extract_keywords(q: str) -> List[str]:
    s = (q or "").strip()
    if not s:
        return []

    low = s.lower()
    tokens = _TOKEN_RE.findall(low)
    kws: List[str] = []

    # keep full query
    compact = re.sub(r"\s+", " ", low).strip()
    if len(compact) >= 3:
        kws.append(compact)

    for t in tokens:
        if len(t) < 2:
            continue
        if t not in kws:
            kws.append(t)

    return kws[:12]


def _concepts_from_query(q: str) -> List[str]:
    """Build *concepts* for phrase search.

    IMPORTANT: We DO NOT want the query to be treated as OR of single tokens.
    So we prioritize bigrams/phrases ("phần cứng", "máy tính") and only add
    unigrams when needed (typically English/alpha-numeric like "cpu", "ram", "linux").
    """

    s = (q or "").strip().lower()
    if not s:
        return []

    raw_tokens = [t for t in _TOKEN_RE.findall(s) if t]
    tokens = [t for t in raw_tokens if t not in _STOP and len(t) >= 2]
    if not tokens:
        return []

    concepts: List[str] = []

    # 1) Bigrams first (phrase intent)
    for i in range(len(tokens) - 1):
        a, b = tokens[i], tokens[i + 1]
        if len(a) < 2 or len(b) < 2:
            continue
        bg = f"{a} {b}".strip()
        if bg not in concepts:
            concepts.append(bg)

    # 2) Add alpha-numeric unigrams (CPU/RAM/Linux/Neo4j...) to not lose intent
    for t in tokens:
        if re.search(r"[0-9A-Za-z]", t) and len(t) >= 3:
            if t not in concepts:
                concepts.append(t)

    # 3) Fallback: if we failed to build bigrams (single-word query, etc.)
    if not concepts:
        for t in tokens:
            if len(t) >= 3 and t not in concepts:
                concepts.append(t)

    return concepts[:6]


def _lex_terms_from_keywords(kws: List[str]) -> List[str]:
    """Pick a small set of terms for lexical matching.

    We primarily care about phrases like 'thông tin' and a few longer tokens.
    """
    out: List[str] = []
    for k in kws:
        k = (k or "").strip()
        if len(k) < 3:
            continue
        # keep the full phrase
        if " " in k:
            if k not in out:
                out.append(k)
            continue
        # keep only longer tokens to avoid too-broad matches
        # BUT allow short alpha-numeric (cpu/ram) too.
        if (len(k) >= 4 or (re.search(r"[0-9A-Za-z]", k) and len(k) >= 3)) and k not in out:
            out.append(k)
    return out[:6]


def _cosine(a: List[float], b: List[float]) -> float:
    if not a or not b:
        return 0.0
    n = min(len(a), len(b))
    dot = 0.0
    na = 0.0
    nb = 0.0
    for i in range(n):
        x = float(a[i])
        y = float(b[i])
        dot += x * y
        na += x * x
        nb += y * y
    den = math.sqrt(na) * math.sqrt(nb)
    return float(dot / den) if den > 0 else 0.0


def _valid_object_id_hex(s: str) -> bool:
    if not s or len(s) != 24:
        return False
    try:
        int(s, 16)
        return True
    except Exception:
        return False


def _status_visible(doc: dict) -> bool:
    # bạn dùng activity/hidden, đôi khi active
    st = (doc or {}).get("status")
    return st not in {"hidden", "HIDDEN"}


def _read_keywords_from_chunk_doc(doc: Optional[dict]) -> List[str]:
    if not doc:
        return []

    # common variants seen across your repo
    for k in ("keywordItems", "keywords", "keyword", "keyword_names", "keywordNames"):
        v = doc.get(k)
        if not v:
            continue

        # list of strings
        if isinstance(v, list) and (len(v) == 0 or isinstance(v[0], str)):
            return [str(x) for x in v if str(x).strip()]

        # list of dicts like {keywordName: ...}
        if isinstance(v, list) and len(v) > 0 and isinstance(v[0], dict):
            out = []
            for it in v:
                name = it.get("keywordName") or it.get("name")
                if name:
                    out.append(str(name))
            return out

        # string
        if isinstance(v, str):
            return [v]

    return []


def _candidate_chunk_ids_from_filters_pg(
    *,
    pg: Session,
    classID: str,
    subjectID: str,
    topicID: str,
    lessonID: str,
) -> Optional[List[str]]:
    """Return list of chunk_ids to restrict scan, or None for no restriction."""
    try:
        if lessonID:
            rows = list(pg.execute(select(Chunk.chunk_id).where(Chunk.lesson_id == lessonID)).all())
            return [r[0] for r in rows]

        if topicID:
            stmt = (
                select(Chunk.chunk_id)
                .join(Lesson, Lesson.lesson_id == Chunk.lesson_id)
                .where(Lesson.topic_id == topicID)
            )
            rows = list(pg.execute(stmt).all())
            return [r[0] for r in rows]

        if subjectID:
            stmt = (
                select(Chunk.chunk_id)
                .join(Lesson, Lesson.lesson_id == Chunk.lesson_id)
                .join(Topic, Topic.topic_id == Lesson.topic_id)
                .where(Topic.subject_id == subjectID)
            )
            rows = list(pg.execute(stmt).all())
            return [r[0] for r in rows]

        if classID:
            stmt = (
                select(Chunk.chunk_id)
                .join(Lesson, Lesson.lesson_id == Chunk.lesson_id)
                .join(Topic, Topic.topic_id == Lesson.topic_id)
                .join(Subject, Subject.subject_id == Topic.subject_id)
                .where(Subject.class_id == classID)
            )
            rows = list(pg.execute(stmt).all())
            return [r[0] for r in rows]

        return None
    except Exception:
        return None


def _load_by_oids(mongo_db, col: str, oid_hex_list: List[str]) -> Dict[str, dict]:
    """Return map oid_hex -> doc. No category filter."""
    out: Dict[str, dict] = {}
    if mongo_db is None or not oid_hex_list:
        return out
    try:
        oids = [ObjectId(x) for x in oid_hex_list if _valid_object_id_hex(x)]
        if not oids:
            return out
        docs = list(mongo_db[col].find({"_id": {"$in": oids}}))
        for d in docs:
            out[str(d.get("_id"))] = d
    except Exception:
        return out
    return out



def _media_sort_key(x: dict) -> tuple:
    priority = {"chunk": 0, "lesson": 1, "topic": 2, "subject": 3}
    return (priority.get((x or {}).get("followType"), 99), ((x or {}).get("name") or "").lower())


def _build_media_item(doc: Optional[dict], *, media_type: str, follow_type: str, follow_id: str, pg_id: str) -> Optional[dict]:
    if not doc or not _status_visible(doc):
        return None

    if media_type == "image":
        name = doc.get("imgName") or doc.get("mapID") or pg_id
        desc = doc.get("imgDescription") or ""
        url = doc.get("imgUrl") or ""
    else:
        name = doc.get("videoName") or doc.get("mapID") or pg_id
        desc = doc.get("videoDescription") or ""
        url = doc.get("videoUrl") or ""

    return {
        "type": media_type,
        "id": pg_id,
        "name": name,
        "description": desc,
        "url": url,
        "mapID": doc.get("mapID") or "",
        "mongoID": str(doc.get("_id")) if doc.get("_id") is not None else "",
        "followType": follow_type,
        "followID": follow_id,
    }


def _load_media_map_for_targets(*, pg: Session, mongo_db, targets: List[tuple[str, str]]) -> Dict[tuple[str, str], dict]:
    out: Dict[tuple[str, str], dict] = {}
    uniq_targets = []
    seen_targets = set()
    for ft, fid in targets:
        key = ((ft or "").strip(), (fid or "").strip())
        if not key[0] or not key[1] or key in seen_targets:
            continue
        seen_targets.add(key)
        uniq_targets.append(key)

    if not uniq_targets:
        return out

    image_rows = []
    video_rows = []
    try:
        conds = [((Image.follow_type == ft) & (Image.follow_id == fid)) for ft, fid in uniq_targets]
        if conds:
            image_rows = list(pg.execute(select(Image.img_id, Image.mongo_id, Image.follow_type, Image.follow_id).where(or_(*conds))).all())
    except Exception:
        image_rows = []

    try:
        conds = [((Video.follow_type == ft) & (Video.follow_id == fid)) for ft, fid in uniq_targets]
        if conds:
            video_rows = list(pg.execute(select(Video.video_id, Video.mongo_id, Video.follow_type, Video.follow_id).where(or_(*conds))).all())
    except Exception:
        video_rows = []

    image_oids = [mongo_id for _pgid, mongo_id, _ft, _fid in image_rows if _valid_object_id_hex(mongo_id or "")]
    video_oids = [mongo_id for _pgid, mongo_id, _ft, _fid in video_rows if _valid_object_id_hex(mongo_id or "")]

    images_by_oid = _load_by_oids(mongo_db, "images", image_oids)
    videos_by_oid = _load_by_oids(mongo_db, "videos", video_oids)

    for img_id, mongo_id, follow_type, follow_id in image_rows:
        doc = images_by_oid.get(mongo_id or "")
        item = _build_media_item(doc, media_type="image", follow_type=follow_type, follow_id=follow_id, pg_id=img_id)
        if not item:
            continue
        key = (follow_type, follow_id)
        bucket = out.setdefault(key, {"images": [], "videos": []})
        bucket["images"].append(item)

    for video_id, mongo_id, follow_type, follow_id in video_rows:
        doc = videos_by_oid.get(mongo_id or "")
        item = _build_media_item(doc, media_type="video", follow_type=follow_type, follow_id=follow_id, pg_id=video_id)
        if not item:
            continue
        key = (follow_type, follow_id)
        bucket = out.setdefault(key, {"images": [], "videos": []})
        bucket["videos"].append(item)

    for bucket in out.values():
        bucket["images"].sort(key=_media_sort_key)
        bucket["videos"].sort(key=_media_sort_key)

    return out



def _pg_chunks_matching_terms(
    *,
    pg: Session,
    terms: List[str],
    cand_chunks: Optional[List[str]],
) -> List[str]:
    """Return chunk_ids where keyword_name or chunk_name ILIKE any term."""
    if not terms:
        return []

    out: List[str] = []
    seen: set[str] = set()

    try:
        cond = or_(*[Keyword.keyword_name.ilike(_like_pat(t)) for t in terms if t])
        stmt = select(Keyword.chunk_id).where(cond)
        if cand_chunks is not None:
            if len(cand_chunks) == 0:
                return []
            stmt = stmt.where(Keyword.chunk_id.in_(cand_chunks))
        rows = list(pg.execute(stmt).all())
        for (cid,) in rows:
            if cid and cid not in seen:
                seen.add(cid)
                out.append(cid)
    except Exception:
        pass

    try:
        cond2 = or_(*[Chunk.chunk_name.ilike(_like_pat(t)) for t in terms if t])
        stmt2 = select(Chunk.chunk_id).where(cond2)
        if cand_chunks is not None:
            if len(cand_chunks) == 0:
                return out
            stmt2 = stmt2.where(Chunk.chunk_id.in_(cand_chunks))
        rows2 = list(pg.execute(stmt2).all())
        for (cid,) in rows2:
            if cid and cid not in seen:
                seen.add(cid)
                out.append(cid)
    except Exception:
        pass

    return out


def _pg_chunks_matching_terms_min_hits(
    *,
    pg: Session,
    terms: List[str],
    cand_chunks: Optional[List[str]],
    min_hits: int,
) -> List[str]:
    """Return chunk_ids where >= min_hits distinct terms match (AND-ish).

    Matching sources:
      - Keyword.keyword_name ILIKE
      - Chunk.chunk_name ILIKE

    Patterns are tolerant to '_' vs ' ' (see _like_pat).
    """

    if not terms:
        return []

    if min_hits <= 1:
        return _pg_chunks_matching_terms(pg=pg, terms=terms, cand_chunks=cand_chunks)

    counts: Dict[str, int] = defaultdict(int)

    def _chunk_ids_for_term(t: str) -> set[str]:
        pat = _like_pat(t)
        ids: set[str] = set()
        try:
            stmt = select(Keyword.chunk_id).where(Keyword.keyword_name.ilike(pat))
            if cand_chunks is not None:
                if len(cand_chunks) == 0:
                    return set()
                stmt = stmt.where(Keyword.chunk_id.in_(cand_chunks))
            rows = list(pg.execute(stmt).all())
            ids |= {cid for (cid,) in rows if cid}
        except Exception:
            pass

        try:
            stmt2 = select(Chunk.chunk_id).where(Chunk.chunk_name.ilike(pat))
            if cand_chunks is not None:
                if len(cand_chunks) == 0:
                    return ids
                stmt2 = stmt2.where(Chunk.chunk_id.in_(cand_chunks))
            rows2 = list(pg.execute(stmt2).all())
            ids |= {cid for (cid,) in rows2 if cid}
        except Exception:
            pass

        return ids

    try:
        for t in terms:
            if not t:
                continue
            ids = _chunk_ids_for_term(t)
            for cid in ids:
                counts[cid] += 1

        return [cid for cid, c in counts.items() if c >= int(min_hits)]
    except Exception:
        return []


def _pick_anchor_concepts(*, pg: Session, concepts: List[str], cand_chunks: Optional[List[str]]) -> List[str]:
    """Pick the strongest single anchor concept when full strict coverage fails.

    Heuristic:
      - prefer longer phrases (more tokens)
      - among same length, prefer the one with fewer hits (more specific)
      - preserve query order as final tie-breaker

    This avoids broad OR behavior while still letting queries like
    'phần cứng máy tính' return CPU chunks through the strongest anchor phrase.
    """

    scored: List[tuple[int, int, int, str]] = []
    for idx, concept in enumerate(concepts):
        if not concept:
            continue
        hit_ids = _pg_chunks_matching_terms(pg=pg, terms=[concept], cand_chunks=cand_chunks)
        if not hit_ids:
            continue
        token_len = len([t for t in concept.split(" ") if t])
        scored.append((-token_len, len(hit_ids), idx, concept))

    if not scored:
        return []

    scored.sort()
    return [scored[0][3]]



def semantic_search(
    *,
    q: str,
    category: str,
    classID: str,
    subjectID: str,
    topicID: str,
    lessonID: str,
    limit: int,
    offset: int,
    username: str,
    pg: Session,
    neo,
    mongo_db,
    debug: bool = False,
) -> dict:
    """Semantic search (chunk-only), with phrase-aware lexical gating + media hydrate.

    Behavior:
      - Try strict coverage first for multi-word queries.
      - If strict coverage fails, fall back to the strongest matching anchor phrase
        instead of returning empty immediately. This keeps results useful for
        queries like 'phần cứng máy tính' -> CPU chunk.
    """

    query = (q or "").strip()
    if not query:
        return {"total": 0, "items": []}

    dbg: Dict[str, object] = {"service_version": _SERVICE_VERSION, "category": category}

    # Candidate restriction by filters (PG graph)
    cand_chunks = _candidate_chunk_ids_from_filters_pg(
        pg=pg, classID=classID, subjectID=subjectID, topicID=topicID, lessonID=lessonID
    )

    tokens = _tokens_no_stop(query)
    strict_mode = len(tokens) >= 2
    fallback_anchor_used = False

    # 1) Build concepts
    if strict_mode:
        concepts = _segment_concepts_strict(pg=pg, tokens=tokens, cand_chunks=cand_chunks)
        dbg["strict_mode"] = True
        dbg["query_tokens"] = tokens
        dbg["query_concepts"] = concepts[:]

        if concepts:
            must_coverage = len(concepts)
            lex_terms = concepts
            lex_chunk_ids = _pg_chunks_matching_terms_min_hits(
                pg=pg, terms=lex_terms, cand_chunks=cand_chunks, min_hits=must_coverage
            )
            dbg["lex_terms"] = lex_terms
            dbg["must_coverage"] = must_coverage
            dbg["lex_chunk_hits"] = len(lex_chunk_ids)

            if lex_chunk_ids:
                restrict_chunk_ids = lex_chunk_ids
            else:
                concepts_partial, covered = _segment_concepts_partial(pg=pg, tokens=tokens, cand_chunks=cand_chunks)
                anchor_concepts = _pick_anchor_concepts(pg=pg, concepts=concepts_partial, cand_chunks=cand_chunks)
                dbg["query_concepts_partial"] = concepts_partial
                dbg["covered_tokens_partial"] = covered
                dbg["anchor_concepts"] = anchor_concepts
                if not anchor_concepts:
                    res = {"total": 0, "items": []}
                    if debug:
                        dbg["reason"] = "strict_mode_no_anchor_hits"
                        res["debug"] = dbg
                    return res
                concepts = anchor_concepts
                restrict_chunk_ids = _pg_chunks_matching_terms_min_hits(
                    pg=pg, terms=anchor_concepts, cand_chunks=cand_chunks, min_hits=1
                )
                fallback_anchor_used = True
        else:
            concepts_partial, covered = _segment_concepts_partial(pg=pg, tokens=tokens, cand_chunks=cand_chunks)
            anchor_concepts = _pick_anchor_concepts(pg=pg, concepts=concepts_partial, cand_chunks=cand_chunks)
            dbg["query_concepts_partial"] = concepts_partial
            dbg["covered_tokens_partial"] = covered
            dbg["anchor_concepts"] = anchor_concepts

            if not anchor_concepts:
                res = {"total": 0, "items": []}
                if debug:
                    dbg["reason"] = "strict_mode_no_full_coverage_or_anchor"
                    res["debug"] = dbg
                return res

            concepts = anchor_concepts
            restrict_chunk_ids = _pg_chunks_matching_terms_min_hits(
                pg=pg, terms=anchor_concepts, cand_chunks=cand_chunks, min_hits=1
            )
            dbg["lex_terms"] = anchor_concepts
            dbg["must_coverage"] = 1
            dbg["lex_chunk_hits"] = len(restrict_chunk_ids)
            fallback_anchor_used = True

        if not restrict_chunk_ids:
            res = {"total": 0, "items": []}
            if debug:
                dbg["reason"] = "strict_mode_no_lex_hits"
                res["debug"] = dbg
            return res

    else:
        concepts = _concepts_from_query(query)
        dbg["strict_mode"] = False
        dbg["query_concepts"] = concepts[:]

        if not concepts:
            return {"total": 0, "items": []}

        # legacy: require >=2 concept coverage when we have 2+ concepts
        must_coverage = 2 if len(concepts) >= 2 else 1

        # Lexical filter (coverage-aware). Only restrict if it yields anything.
        lex_terms = _lex_terms_from_keywords(concepts)
        lex_chunk_ids = _pg_chunks_matching_terms_min_hits(
            pg=pg, terms=lex_terms, cand_chunks=cand_chunks, min_hits=must_coverage
        )
        dbg["lex_terms"] = lex_terms
        dbg["lex_chunk_hits"] = len(lex_chunk_ids)
        dbg["must_coverage"] = must_coverage

        restrict_chunk_ids = lex_chunk_ids if lex_chunk_ids else cand_chunks

    dbg["fallback_anchor_used"] = fallback_anchor_used

    seed_chunk_ids = list(restrict_chunk_ids or [])
    dbg["seed_chunk_ids"] = seed_chunk_ids[:]

    exact_hit_count = len(seed_chunk_ids)
    core_query = _core_query_text(query)
    max_expand_terms = _max_expand_terms(core_query, tokens, exact_hit_count)
    allow_gemini_expand = bool(core_query) and max_expand_terms > 0
    if not core_query:
        expand_reason = "blocked_empty_core_query"
    elif max_expand_terms <= 0:
        if _is_generic_query(core_query, tokens):
            expand_reason = "blocked_generic_query"
        else:
            expand_reason = f"blocked_exact_hits_{exact_hit_count}"
    else:
        expand_reason = "specific_parent_topic"
    dbg["core_query"] = core_query
    dbg["allow_gemini_expand"] = allow_gemini_expand
    dbg["gemini_expand_reason"] = expand_reason
    dbg["max_expand_terms"] = max_expand_terms

    gemini_terms: List[str] = []
    gemini_hit_ids: List[str] = []
    gem_dbg = {}
    if allow_gemini_expand:
        try:
            gemini_terms, gem_dbg = expand_topic_keywords_debug(core_query, None)
        except Exception as e:
            gemini_terms = []
            gem_dbg = {"error": f"unexpected:{e}"}

    if gemini_terms:
        gemini_terms = _filter_terms_with_db_hits(
            pg=pg,
            terms=gemini_terms,
            cand_chunks=cand_chunks,
            limit=max_expand_terms,
        )

    if gemini_terms:
        gemini_hit_ids = _pg_chunks_matching_terms(pg=pg, terms=gemini_terms, cand_chunks=cand_chunks)
        if gemini_hit_ids:
            restrict_chunk_ids = _merge_seed_and_expanded(seed_chunk_ids, gemini_hit_ids, max_extra=12)
        else:
            restrict_chunk_ids = seed_chunk_ids

        for term in gemini_terms:
            if term and term not in concepts:
                concepts.append(term)

    dbg["gemini_terms"] = gemini_terms
    dbg["gemini_hit_ids"] = len(gemini_hit_ids)
    if gem_dbg:
        if gem_dbg.get("model"):
            dbg["gemini_model"] = gem_dbg.get("model")
        if gem_dbg.get("error"):
            dbg["gemini_error"] = gem_dbg.get("error")
        if gem_dbg.get("raw_text"):
            dbg["gemini_raw_text"] = gem_dbg.get("raw_text")
        if "key_count" in gem_dbg:
            dbg["gemini_key_count"] = gem_dbg.get("key_count")
        if "key_slot" in gem_dbg:
            dbg["gemini_key_slot"] = gem_dbg.get("key_slot")
        if "attempt" in gem_dbg:
            dbg["gemini_attempt"] = gem_dbg.get("attempt")
        if gem_dbg.get("mode"):
            dbg["gemini_mode"] = gem_dbg.get("mode")

    parent_phrase_ids: List[str] = []
    if core_query:
        try:
            parent_phrase_ids = _pg_chunks_matching_terms(
                pg=pg,
                terms=[core_query],
                cand_chunks=restrict_chunk_ids if restrict_chunk_ids is not None else cand_chunks,
            )
        except Exception:
            parent_phrase_ids = []
    dbg["parent_phrase_hits"] = len(parent_phrase_ids)

    dbg["ranking_concepts"] = concepts[:]

    # 2) Embed concepts (for ranking)
    q_embs = [embed_keyword_cached(c) for c in concepts]

    # 3) Load PG keywords with embeddings (also load keyword_name for transparency)
    try:
        stmt = (
            select(Keyword.keyword_embedding, Keyword.chunk_id, Keyword.keyword_name)
            .where(Keyword.keyword_embedding.isnot(None))
        )

        if restrict_chunk_ids is not None:
            if len(restrict_chunk_ids) == 0:
                res = {"total": 0, "items": []}
                if debug:
                    dbg["pg_rows_with_embedding"] = 0
                    dbg["ranked_chunks"] = 0
                    res["debug"] = dbg
                return res
            stmt = stmt.where(Keyword.chunk_id.in_(restrict_chunk_ids))

        rows = list(pg.execute(stmt).all())
    except SQLAlchemyError:
        rows = []

    dbg["pg_rows_with_embedding"] = len(rows)

    # 4) Score per chunk
    chunk_top_kw: Dict[str, List[Tuple[float, str]]] = {}

    if strict_mode:
        # Strict/anchor mode: lexical filtering already narrows candidates.
        # Use embedding only for ranking; do not drop chunks on cosine thresholds.
        chunk_concept_best: Dict[str, List[float]] = defaultdict(lambda: [0.0] * len(q_embs))

        for emb, chunk_id, kw_name in rows:
            if not chunk_id or not emb:
                continue
            vec = list(emb)
            bests = chunk_concept_best[chunk_id]

            max_for_kw = 0.0
            for i, qe in enumerate(q_embs):
                sim = _cosine(vec, qe)
                if sim > max_for_kw:
                    max_for_kw = sim
                if sim > bests[i]:
                    bests[i] = sim

            if kw_name:
                arr = chunk_top_kw.get(chunk_id, [])
                arr.append((max_for_kw, str(kw_name)))
                arr.sort(key=lambda x: x[0], reverse=True)
                chunk_top_kw[chunk_id] = arr[:5]

        chunk_score: Dict[str, float] = {}
        seed_set = set(seed_chunk_ids)
        gemini_set = set(gemini_hit_ids)
        parent_phrase_set = set(parent_phrase_ids)
        parent_phrase_boost = 1.25 if allow_gemini_expand and parent_phrase_set else 0.0
        child_hit_boost = 0.18
        child_nonseed_boost = 0.10

        for cid in restrict_chunk_ids or []:
            bests = chunk_concept_best.get(cid, [0.0] * len(q_embs))
            coverage = sum(1 for s in bests if s > 0.0)
            score = float(sum(bests)) + 0.05 * float(coverage)

            # Prefer the exact/phrase parent document over expanded child documents.
            # This keeps topic queries stable in the future: overview doc first,
            # child docs like CPU/RAM/GPU right below it.
            if cid in parent_phrase_set:
                score += parent_phrase_boost
                if cid in seed_set:
                    score += 0.20

            if cid in gemini_set:
                score += child_hit_boost
                if cid not in seed_set:
                    score += child_nonseed_boost

            if cid in seed_set:
                score += 0.05

            chunk_score[cid] = score

        ranked: List[Tuple[str, float]] = sorted(chunk_score.items(), key=lambda x: x[1], reverse=True)
        dbg["ranked_chunks"] = len(ranked)
        dbg["lex_mode"] = True
        dbg["sim_th"] = "disabled_in_strict_or_anchor_mode"
        dbg["child_boost_hits"] = len(gemini_set)
        dbg["parent_phrase_boost"] = parent_phrase_boost

    else:
        # Non-strict: keep coverage + threshold to avoid OR behavior.
        SIM_TH = 0.18 if must_coverage >= 2 else 0.22

        chunk_concept_best: Dict[str, List[float]] = defaultdict(lambda: [0.0] * len(q_embs))

        for emb, chunk_id, kw_name in rows:
            if not chunk_id or not emb:
                continue

            vec = list(emb)
            bests = chunk_concept_best[chunk_id]

            max_for_kw = 0.0
            for i, qe in enumerate(q_embs):
                sim = _cosine(vec, qe)
                if sim > max_for_kw:
                    max_for_kw = sim
                if sim > bests[i]:
                    bests[i] = sim

            if kw_name:
                arr = chunk_top_kw.get(chunk_id, [])
                arr.append((max_for_kw, str(kw_name)))
                arr.sort(key=lambda x: x[0], reverse=True)
                chunk_top_kw[chunk_id] = arr[:5]

        chunk_score: Dict[str, float] = {}
        for cid, bests in chunk_concept_best.items():
            coverage = sum(1 for s in bests if s >= SIM_TH)
            if coverage < must_coverage:
                continue
            score = float(sum(bests)) + 0.15 * float(coverage)
            if coverage == len(bests) and len(bests) >= 2:
                score += 0.10
            chunk_score[cid] = score

        ranked = sorted(chunk_score.items(), key=lambda x: x[1], reverse=True)
        dbg["ranked_chunks"] = len(ranked)
        dbg["lex_mode"] = False
        dbg["sim_th"] = SIM_TH

    if not ranked:
        res = {"total": 0, "items": []}
        if debug:
            res["debug"] = dbg
        return res

    page_pairs = ranked[offset : offset + limit]
    page_chunk_ids = [cid for cid, _ in page_pairs]
    score_by_chunk = dict(page_pairs)

    # 5) Fetch chunk + hierarchy from PG
    try:
        stmt = (
            select(
                Chunk.chunk_id,
                Chunk.chunk_name,
                Chunk.chunk_type,
                Chunk.mongo_id,
                Lesson.lesson_id,
                Lesson.lesson_name,
                Lesson.mongo_id,
                Topic.topic_id,
                Topic.topic_name,
                Topic.mongo_id,
                Subject.subject_id,
                Subject.subject_name,
                Subject.mongo_id,
                Class.class_id,
                Class.class_name,
                Class.mongo_id,
            )
            .join(Lesson, Lesson.lesson_id == Chunk.lesson_id)
            .join(Topic, Topic.topic_id == Lesson.topic_id)
            .join(Subject, Subject.subject_id == Topic.subject_id)
            .join(Class, Class.class_id == Subject.class_id)
            .where(Chunk.chunk_id.in_(page_chunk_ids))
        )
        pg_rows = list(pg.execute(stmt).all())
    except SQLAlchemyError:
        pg_rows = []

    dbg["pg_chunk_rows"] = len(pg_rows)

    # Map chunk_id -> hierarchy/meta
    pg_map: Dict[str, dict] = {}
    chunk_mongo_hex: List[str] = []
    lesson_mongo_hex: List[str] = []
    topic_mongo_hex: List[str] = []
    subject_mongo_hex: List[str] = []

    for r in pg_rows:
        (
            chunk_id,
            chunk_name,
            chunk_type,
            chunk_mongo_id,
            lesson_id_v,
            lesson_name,
            lesson_mongo_id,
            topic_id_v,
            topic_name,
            topic_mongo_id,
            subject_id_v,
            subject_name,
            subject_mongo_id,
            class_id_v,
            class_name,
            class_mongo_id,
        ) = r

        pg_map[chunk_id] = {
            "chunkID": chunk_id,
            "chunkName": chunk_name,
            "chunkType": chunk_type,
            "chunkMongoId": chunk_mongo_id,
            "lesson": {"lessonID": lesson_id_v, "lessonName": lesson_name, "mongoId": lesson_mongo_id},
            "topic": {"topicID": topic_id_v, "topicName": topic_name, "mongoId": topic_mongo_id},
            "subject": {"subjectID": subject_id_v, "subjectName": subject_name, "mongoId": subject_mongo_id},
            "class": {"classID": class_id_v, "className": class_name, "mongoId": class_mongo_id},
        }

        if _valid_object_id_hex(chunk_mongo_id or ""):
            chunk_mongo_hex.append(chunk_mongo_id)
        if _valid_object_id_hex(lesson_mongo_id or ""):
            lesson_mongo_hex.append(lesson_mongo_id)
        if _valid_object_id_hex(topic_mongo_id or ""):
            topic_mongo_hex.append(topic_mongo_id)
        if _valid_object_id_hex(subject_mongo_id or ""):
            subject_mongo_hex.append(subject_mongo_id)

    # 6) Load Mongo docs
    mongo_chunks_by_oid = _load_by_oids(mongo_db, "chunks", chunk_mongo_hex)
    mongo_lessons_by_oid = _load_by_oids(mongo_db, "lessons", lesson_mongo_hex)
    mongo_topics_by_oid = _load_by_oids(mongo_db, "topics", topic_mongo_hex)
    mongo_subjects_by_oid = _load_by_oids(mongo_db, "subjects", subject_mongo_hex)

    dbg["mongo_chunks_raw"] = len(mongo_chunks_by_oid)

    # 6.5) Load media linked to the hierarchy of each page chunk
    media_targets: List[tuple[str, str]] = []
    chunk_targets_by_chunk: Dict[str, List[tuple[str, str]]] = {}
    for cid in page_chunk_ids:
        base = pg_map.get(cid)
        if not base:
            continue
        targets = [
            ("chunk", base.get("chunkID") or ""),
            ("lesson", (base.get("lesson") or {}).get("lessonID") or ""),
            ("topic", (base.get("topic") or {}).get("topicID") or ""),
            ("subject", (base.get("subject") or {}).get("subjectID") or ""),
        ]
        norm_targets = [(ft, fid) for ft, fid in targets if ft and fid]
        chunk_targets_by_chunk[cid] = norm_targets
        media_targets.extend(norm_targets)

    media_map = _load_media_map_for_targets(pg=pg, mongo_db=mongo_db, targets=media_targets)
    dbg["media_target_count"] = len(media_targets)
    dbg["media_hit_groups"] = len(media_map)

    # 7) Build items
    items: List[dict] = []
    dropped_hidden = 0
    dropped_missing_pg_join = 0

    for cid in page_chunk_ids:
        base = pg_map.get(cid)
        if not base:
            dropped_missing_pg_join += 1
            continue

        s = float(score_by_chunk.get(cid, 0.0))

        chunk_doc = None
        oid_hex = base.get("chunkMongoId")
        if _valid_object_id_hex(oid_hex or ""):
            chunk_doc = mongo_chunks_by_oid.get(oid_hex)

        if chunk_doc and not _status_visible(chunk_doc):
            dropped_hidden += 1
            continue

        if category and category != "all":
            chunk_category = (chunk_doc or {}).get("chunkCategory") or ""
            if chunk_category and chunk_category != category:
                continue

        lesson_doc = None
        topic_doc = None
        subject_doc = None

        l_oid = base["lesson"].get("mongoId")
        t_oid = base["topic"].get("mongoId")
        s_oid = base["subject"].get("mongoId")

        if _valid_object_id_hex(l_oid or ""):
            lesson_doc = mongo_lessons_by_oid.get(l_oid)
        if _valid_object_id_hex(t_oid or ""):
            topic_doc = mongo_topics_by_oid.get(t_oid)
        if _valid_object_id_hex(s_oid or ""):
            subject_doc = mongo_subjects_by_oid.get(s_oid)

        lesson_url = lesson_doc.get("lessonUrl") if (lesson_doc and _status_visible(lesson_doc)) else ""
        topic_url = topic_doc.get("topicUrl") if (topic_doc and _status_visible(topic_doc)) else ""
        subject_url = subject_doc.get("subjectUrl") if (subject_doc and _status_visible(subject_doc)) else ""

        matched_kw = [name for _, name in chunk_top_kw.get(cid, [])]

        images = []
        videos = []
        media_sources = {"chunk": 0, "lesson": 0, "topic": 0, "subject": 0}
        for ft, fid in chunk_targets_by_chunk.get(cid, []):
            bucket = media_map.get((ft, fid)) or {}
            part_images = bucket.get("images") or []
            part_videos = bucket.get("videos") or []
            if part_images or part_videos:
                media_sources[ft] = len(part_images) + len(part_videos)
            images.extend(part_images)
            videos.extend(part_videos)

        images.sort(key=_media_sort_key)
        videos.sort(key=_media_sort_key)

        item = {
            "type": "chunk",
            "id": cid,
            "name": base.get("chunkName") or (chunk_doc.get("chunkName") if chunk_doc else cid),
            "score": s,
            "chunkID": cid,
            "chunkName": (chunk_doc.get("chunkName") if chunk_doc else None) or base.get("chunkName"),
            "chunkType": (chunk_doc.get("chunkType") if chunk_doc else None) or base.get("chunkType"),
            "chunkUrl": (chunk_doc.get("chunkUrl") if chunk_doc else None),
            "chunkDescription": (chunk_doc.get("chunkDescription") if chunk_doc else None),
            "keywords": _read_keywords_from_chunk_doc(chunk_doc),
            "matchedKeywords": matched_kw,
            "images": images,
            "videos": videos,
            "mediaSummary": {
                "totalImages": len(images),
                "totalVideos": len(videos),
                "byFollowType": media_sources,
            },
            "isSaved": False,
            "class": {"classID": base["class"]["classID"], "className": base["class"]["className"]},
            "subject": {
                "subjectID": base["subject"]["subjectID"],
                "subjectName": base["subject"]["subjectName"],
                "subjectDescription": (
                    (subject_doc.get("subjectTitle") if subject_doc else None)
                    or (subject_doc.get("description") if subject_doc else None)
                    or ""
                ),
                "subjectUrl": subject_url,
            },
            "topic": {
                "topicID": base["topic"]["topicID"],
                "topicName": base["topic"]["topicName"],
                "topicDescription": (
                    (topic_doc.get("topicDescription") if topic_doc else None)
                    or (topic_doc.get("topic_description") if topic_doc else None)
                    or (topic_doc.get("description") if topic_doc else None)
                    or ""
                ),
                "topicUrl": topic_url,
            },
            "lesson": {
                "lessonID": base["lesson"]["lessonID"],
                "lessonName": base["lesson"]["lessonName"],
                "lessonDescription": (
                    (lesson_doc.get("lessonDescription") if lesson_doc else None)
                    or (lesson_doc.get("lesson_description") if lesson_doc else None)
                    or (lesson_doc.get("description") if lesson_doc else None)
                    or (lesson_doc.get("lessonType") if lesson_doc else None)
                    or ""
                ),
                "lessonUrl": lesson_url,
                "lessonType": (lesson_doc.get("lessonType") if lesson_doc else None) or "",
            },
            "category": (chunk_doc.get("chunkCategory") if chunk_doc else None) or category or "document",
        }

        try:
            if mongo_db is not None:
                saved = mongo_db["user_saved_chunks"].find_one({"username": username, "chunkID": cid})
                item["isSaved"] = bool(saved)
        except Exception:
            pass

        items.append(item)

    res = {"total": len(items), "items": items}

    if debug:
        dbg["items_built"] = len(items)
        dbg["dropped_hidden"] = dropped_hidden
        dbg["dropped_missing_pg_join"] = dropped_missing_pg_join
        if items:
            dbg["sample_item_match"] = {
                "chunkID": items[0].get("chunkID"),
                "keywords_in_doc": items[0].get("keywords"),
                "matchedKeywords": items[0].get("matchedKeywords"),
            }
        res["debug"] = dbg

    return res